# Generated by Django 4.2.13 on 2024-08-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('instituicao', 'Instituição'), ('aluno', 'Aluno'), ('servidor', 'Servidor')], default='aluno', max_length=20),
        ),
    ]
