# Generated by Django 4.2.13 on 2024-09-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagemsite_instituicao_parceiro_pesquisador_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Pesquisador', 'Pesquisador')], default='Aluno', max_length=30),
        ),
    ]
